public class Constants {

    public static final String wspaceEndpoint = '/workspaces';
    public static  final String formEndpoint = '/forms?workspace_id=';
    public static final String questEndpoint = '/forms/';
    public static final String FORMS_WRAPPER = 'FormsWrapper';
    public static final String WORKSPACE_WRAPPER = 'WorkspaceWrapper';
    public static final String QUESTION_WRAPPER = 'QuestionsWrapper';
    public static final String RESPONSE_WRAPPER = 'ResponseWrapper';
    public static final String DEFAULT_ACCT = 'unlinked answers';
    public static final String CONST_EMAIL = 'email';
    public static final String NAMED_CREDS = 'callout:TypeForm';
    public static final String BOOL_KEY = 'boolean';
    public static final String BOOL_KEY_REP = 'x_boolean';
    public static final String NUM_KEY = 'number';
    public static final String NUM_KEY_REP = 'x_number';
    public static final String ENDPOINT_RESP =  '/responses';
    public static final Integer BTCH_SIZE = 10;
    
}